run dotnet test
PS C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test> dotnet test
Class1.cs(9,20): error CS0161: 'Class1.getLength()': not all code paths return a value [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\model\model.csproj]
PS C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test> dotnet test
Class1Test.cs(1,7): error CS0246: The type or namespace name 'Class1' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(4,6): error CS0246: The type or namespace name 'TestClassAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(4,6): error CS0246: The type or namespace name 'TestClass' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(7,26): error CS0246: The type or namespace name 'Class1' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(14,10): error CS0246: The type or namespace name 'TestMethodAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(14,10): error CS0246: The type or namespace name 'TestMethod' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
PS C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test> dotnet test
Class1Test.cs(1,7): error CS0138: A 'using namespace' directive can only be applied to namespaces; 'Class1' is a type not a namespace. Consider a 'using static'
directive instead [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(4,6): error CS0246: The type or namespace name 'TestClassAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(4,6): error CS0246: The type or namespace name 'TestClass' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(7,26): error CS0246: The type or namespace name 'Class1' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(14,10): error CS0246: The type or namespace name 'TestMethodAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(14,10): error CS0246: The type or namespace name 'TestMethod' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
PS C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test> dotnet test
Class1Test.cs(4,6): error CS0246: The type or namespace name 'TestClassAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(4,6): error CS0246: The type or namespace name 'TestClass' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(14,10): error CS0246: The type or namespace name 'TestMethodAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]
Class1Test.cs(14,10): error CS0246: The type or namespace name 'TestMethod' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\kus\Documents\src\wyoming\experimental\dotnet\openroom\test\test.csproj]