add a tsconfig file
[kus@localhost jonah]$ tsc hackerrank.ts
hackerrank.ts:15:20 - error TS2339: Property 'includes' does not exist on type 'string[]'.

15         if (vowels.includes(s[i])) {
                      ~~~~~~~~

Found 1 error.