try to use aws glacier and fail
(gillette) [kus@asus-vivobook gillette]$ which pip
~/.local/share/virtualenvs/gillette-PKBcjts5/bin/pip
(gillette) [kus@asus-vivobook gillette]$ pip install --upgrade pip setuptools
Requirement already up-to-date: pip in /home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages (19.0.1)
Requirement already up-to-date: setuptools in /home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages (40.6.3)
(gillette) [kus@asus-vivobook gillette]$ pip install boto3
Collecting boto3
  Downloading https://files.pythonhosted.org/packages/c6/f3/be2ffdabba9a53fdc573add8f84325583926e21a8ba3d510b2aa02c06ad9/boto3-1.9.84-py2.py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 1.6MB/s
Collecting botocore<1.13.0,>=1.12.84 (from boto3)
  Downloading https://files.pythonhosted.org/packages/45/5b/0d85af8f526d9058080e6e40c6031afec5424f55ddc31009d506fb9b3356/botocore-1.12.84-py2.py3-none-any.whl (5.2MB)
    100% |████████████████████████████████| 5.2MB 1.4MB/s
Collecting jmespath<1.0.0,>=0.7.1 (from boto3)
  Downloading https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3)
  Downloading https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl (59kB)
    100% |████████████████████████████████| 61kB 1.6MB/s
Collecting python-dateutil<3.0.0,>=2.1; python_version >= "2.7" (from botocore<1.13.0,>=1.12.84->boto3)
  Using cached https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl
Collecting docutils>=0.10 (from botocore<1.13.0,>=1.12.84->boto3)
  Downloading https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl (543kB)
    100% |████████████████████████████████| 552kB 1.8MB/s
Collecting urllib3<1.25,>=1.20; python_version >= "3.4" (from botocore<1.13.0,>=1.12.84->boto3)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore<1.13.0,>=1.12.84->boto3)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, jmespath, docutils, urllib3, botocore, s3transfer, boto3
Successfully installed boto3-1.9.84 botocore-1.12.84 docutils-0.14 jmespath-0.9.3 python-dateutil-2.7.5 s3transfer-0.1.13 six-1.12.0 urllib3-1.24.1
(gillette) [kus@asus-vivobook gillette]$ ls -a
.  ..  .idea  Pipfile
(gillette) [kus@asus-vivobook gillette]$ pipenv install pendulum
Installing pendulum…
✔ Installation Succeeded
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (43dba8)!
Installing dependencies from Pipfile.lock (43dba8)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:01
(gillette) [kus@asus-vivobook gillette]$ pipenv install boto3
Installing boto3…
✔ Installation Succeeded
Pipfile.lock (f2a3ee) out of date, updating to (43dba8)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (f2a3ee)!
Installing dependencies from Pipfile.lock (f2a3ee)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 10/10 — 00:00:03
(gillette) [kus@asus-vivobook gillette]$ pipenv install boto3
Installing boto3…
✔ Installation Succeeded
Installing dependencies from Pipfile.lock (f2a3ee)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 10/10 — 00:00:06
(gillette) [kus@asus-vivobook gillette]$ pipenv install attrs
Installing attrs…
✔ Installation Succeeded
Pipfile.lock (07db15) out of date, updating to (f2a3ee)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (07db15)!
Installing dependencies from Pipfile.lock (07db15)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 11/11 — 00:00:06
(gillette) [kus@asus-vivobook gillette]$
(gillette) [kus@asus-vivobook gillette]$ pipenv install pytest
Installing pytest…
✔ Installation Succeeded
Pipfile.lock (90cff7) out of date, updating to (07db15)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (90cff7)!
Installing dependencies from Pipfile.lock (90cff7)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 16/16 — 00:00:02
(gillette) [kus@asus-vivobook gillette]$ pipenv install requests
Installing requests…
✔ Installation Succeeded
Pipfile.lock (832e15) out of date, updating to (90cff7)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (832e15)!
Installing dependencies from Pipfile.lock (832e15)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 20/20 — 00:00:02
(gillette) [kus@asus-vivobook gillette]$ pipenv install python-dotenv
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing python-dotenv…
✔ Installation Succeeded
Pipfile.lock (8a7135) out of date, updating to (832e15)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (8a7135)!
Installing dependencies from Pipfile.lock (8a7135)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 21/21 — 00:00:11
(gillette) [kus@asus-vivobook gillette]$ ^C
(gillette) [kus@asus-vivobook gillette]$ python my_app.py
AKIAIWO76VOQRYI3XLPQ
(gillette) [kus@asus-vivobook gillette]$ python my_app.py
Traceback (most recent call last):
  File "my_app.py", line 4, in <module>
    glacier = boto3.resource('glacier')
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/session.py", line 838, in create_client
    client_config=config, api_version=api_version)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/client.py", line 86, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/args.py", line 47, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/args.py", line 117, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
(gillette) [kus@asus-vivobook gillette]$ python my_app.py
us-east-1
Traceback (most recent call last):
  File "my_app.py", line 5, in <module>
    glacier = boto3.resource('glacier')
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/session.py", line 838, in create_client
    client_config=config, api_version=api_version)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/client.py", line 86, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/args.py", line 47, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/args.py", line 117, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/home/kus/.local/share/virtualenvs/gillette-PKBcjts5/lib/python3.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
(gillette) [kus@asus-vivobook gillette]$