play with typescript
this is silly

[kus@localhost wyoming]$ cd ~/src/
azure/    lr/       personal/ qc/       wyoming/
[kus@localhost wyoming]$ cd ~/src/wyoming/experimental/typescript/jonah/
[kus@localhost jonah]$ yarn install
yarn install v1.13.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
Done in 0.08s.
[kus@localhost jonah]$ npm install -g typescript
/home/kus/.nvm/versions/node/v11.8.0/bin/tsc -> /home/kus/.nvm/versions/node/v11.8.0/lib/node_modules/typescript/bin/tsc
/home/kus/.nvm/versions/node/v11.8.0/bin/tsserver -> /home/kus/.nvm/versions/node/v11.8.0/lib/node_modules/typescript/bin/tsserver
+ typescript@3.2.4
added 1 package from 1 contributor in 1.542s
[kus@localhost jonah]$ yarn init
yarn init v1.13.0
question name (jonah):
question version (1.0.0):
question description: Jonah is an experiment in Typescript
question entry point (index.js):
question repository url: https://gitlab.com/wyoming/wyoming.gitlab.io
question author: Kushal Hada
question license (MIT): GPLv3
question private:
success Saved package.json
Done in 52.48s.
[kus@localhost jonah]$ yarn add
yarn add v1.13.0
warning package.json: License should be a valid SPDX license expression
error Missing list of packages to add to your project.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
[kus@localhost jonah]$ yarn add
yarn add v1.13.0
error Missing list of packages to add to your project.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
[kus@localhost jonah]$ yarn install
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.06s.
[kus@localhost jonah]$ yarn add typescript
yarn add v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ typescript@3.2.4
info All dependencies
└─ typescript@3.2.4
Done in 0.70s.
[kus@localhost jonah]$ which tsc
~/.nvm/versions/node/v11.8.0/bin/tsc
[kus@localhost jonah]$ node_modules
node_modules
[kus@localhost jonah]$ ls -a node_modules/
.bin/            typescript/      .yarn-integrity
[kus@localhost jonah]$ ls -a node_modules/.bin/ts
tsc       tsserver
[kus@localhost jonah]$ ls -a node_modules/.bin/tsc main.ts
main.ts  node_modules/.bin/tsc
[kus@localhost jonah]$ ls -a node_modules/.bin/tsc main.ts
main.ts  node_modules/.bin/tsc
[kus@localhost jonah]$ tsc main.ts
[kus@localhost jonah]$ tsc main.js
error TS6054: File 'main.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.

Found 1 error.

[kus@localhost jonah]$ tsc main.ts
error TS6053: File 'main.ts' not found.

Found 1 error.

[kus@localhost jonah]$ tsc index.ts
[kus@localhost jonah]$ tsc index.ts
[kus@localhost jonah]$ tsc index.ts
[kus@localhost jonah]$ yarn run index.js
yarn run v1.13.0
error Command "index.js" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[kus@localhost jonah]$ dnf info rhino
Last metadata expiration check: 1 day, 13:03:04 ago on Thu 24 Jan 2019 10:39:43 PM EST.
Available Packages
Name         : rhino
Version      : 1.7.7.1
Release      : 6.fc29
Arch         : noarch
Size         : 1.1 M
Source       : rhino-1.7.7.1-6.fc29.src.rpm
Repo         : fedora
Summary      : JavaScript for Java
URL          : http://www.mozilla.org/rhino/
License      : MPLv2.0
Description  : Rhino is an open-source implementation of JavaScript written entirely
             : in Java. It is typically embedded into Java applications to provide
             : scripting to end users.

[kus@localhost jonah]$ sudo dnf install rhino
[sudo] password for kus:
Fedora Modular 29 - x86_64                                                                                                                                      15 kB/s |  18 kB     00:01
Fedora Modular 29 - x86_64 - Updates                                                                                                                            12 kB/s |  18 kB     00:01
Fedora 29 - x86_64 - Updates                                                                                                                                    15 kB/s |  18 kB     00:01
Fedora 29 - x86_64 - Updates                                                                                                                                   3.1 MB/s |  20 MB     00:06
Fedora 29 - x86_64                                                                                                                                              15 kB/s |  18 kB     00:01
google-chrome                                                                                                                                                  1.2 kB/s | 1.3 kB     00:01
Dependencies resolved.
===============================================================================================================================================================================================
 Package                                              Arch                                     Version                                          Repository                                Size
===============================================================================================================================================================================================
Installing:
 rhino                                                noarch                                   1.7.7.1-6.fc29                                   fedora                                   1.1 M
Installing dependencies:
 hawtjni-runtime                                      noarch                                   1.16-3.fc29                                      fedora                                    39 k
 jansi                                                noarch                                   1.17.1-2.fc29                                    fedora                                    76 k
 jansi-native                                         x86_64                                   1.7-7.fc29                                       fedora                                    71 k
 javapackages-tools                                   noarch                                   5.3.0-1.fc29                                     fedora                                    33 k
 jline                                                noarch                                   2.14.6-3.fc29                                    fedora                                   151 k

Transaction Summary
===============================================================================================================================================================================================
Install  6 Packages

Total download size: 1.5 M
Installed size: 1.7 M
Is this ok [y/N]: y
Downloading Packages:
(1/6): hawtjni-runtime-1.16-3.fc29.noarch.rpm                                                                                                                   27 kB/s |  39 kB     00:01
(2/6): jansi-1.17.1-2.fc29.noarch.rpm                                                                                                                           51 kB/s |  76 kB     00:01
(3/6): jansi-native-1.7-7.fc29.x86_64.rpm                                                                                                                       46 kB/s |  71 kB     00:01
(4/6): javapackages-tools-5.3.0-1.fc29.noarch.rpm                                                                                                              283 kB/s |  33 kB     00:00
(5/6): jline-2.14.6-3.fc29.noarch.rpm                                                                                                                          772 kB/s | 151 kB     00:00
(6/6): rhino-1.7.7.1-6.fc29.noarch.rpm                                                                                                                         2.2 MB/s | 1.1 MB     00:00
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                          467 kB/s | 1.5 MB     00:03
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                       1/1
  Installing       : javapackages-tools-5.3.0-1.fc29.noarch                                                                                                                                1/6
  Installing       : hawtjni-runtime-1.16-3.fc29.noarch                                                                                                                                    2/6
  Installing       : jansi-native-1.7-7.fc29.x86_64                                                                                                                                        3/6
  Installing       : jansi-1.17.1-2.fc29.noarch                                                                                                                                            4/6
  Installing       : jline-2.14.6-3.fc29.noarch                                                                                                                                            5/6
  Installing       : rhino-1.7.7.1-6.fc29.noarch                                                                                                                                           6/6
  Running scriptlet: rhino-1.7.7.1-6.fc29.noarch                                                                                                                                           6/6
  Verifying        : hawtjni-runtime-1.16-3.fc29.noarch                                                                                                                                    1/6
  Verifying        : jansi-1.17.1-2.fc29.noarch                                                                                                                                            2/6
  Verifying        : jansi-native-1.7-7.fc29.x86_64                                                                                                                                        3/6
  Verifying        : javapackages-tools-5.3.0-1.fc29.noarch                                                                                                                                4/6
  Verifying        : jline-2.14.6-3.fc29.noarch                                                                                                                                            5/6
  Verifying        : rhino-1.7.7.1-6.fc29.noarch                                                                                                                                           6/6

Installed:
  rhino-1.7.7.1-6.fc29.noarch hawtjni-runtime-1.16-3.fc29.noarch jansi-1.17.1-2.fc29.noarch jansi-native-1.7-7.fc29.x86_64 javapackages-tools-5.3.0-1.fc29.noarch jline-2.14.6-3.fc29.noarch

Complete!
[kus@localhost jonah]$ rhino index.js
[kus@localhost jonah]$ tsc index.ts
[kus@localhost jonah]$ rhino index.js
js: uncaught JavaScript runtime exception: ReferenceError: "console" is not defined.

[kus@localhost jonah]$ rhino index.js
js: uncaught JavaScript runtime exception: ReferenceError: "console" is not defined.

[kus@localhost jonah]$ tsc index.ts
[kus@localhost jonah]$ rhino index.js
js: uncaught JavaScript runtime exception: ReferenceError: "window" is not defined.

[kus@localhost jonah]$ tsc index.ts
index.ts:15:1 - error TS2554: Expected 0 arguments, but got 1.

15 print(greeter("user"));
   ~~~~~~~~~~~~~~~~~~~~~~

Found 1 error.

[kus@localhost jonah]$ tsc index.ts
[kus@localhost jonah]$ rhino index.js
[kus@localhost jonah]$ sudo dnf remove rhino
Dependencies resolved.
===============================================================================================================================================================================================
 Package                                             Arch                                    Version                                            Repository                                Size
===============================================================================================================================================================================================
Removing:
 rhino                                               noarch                                  1.7.7.1-6.fc29                                     @fedora                                  1.2 M
Removing unused dependencies:
 hawtjni-runtime                                     noarch                                  1.16-3.fc29                                        @fedora                                   56 k
 jansi                                               noarch                                  1.17.1-2.fc29                                      @fedora                                  106 k
 jansi-native                                        x86_64                                  1.7-7.fc29                                         @fedora                                  103 k
 javapackages-tools                                  noarch                                  5.3.0-1.fc29                                       @fedora                                   69 k
 jline                                               noarch                                  2.14.6-3.fc29                                      @fedora                                  168 k

Transaction Summary
===============================================================================================================================================================================================
Remove  6 Packages

Freed space: 1.7 M
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                       1/1
  Erasing          : rhino-1.7.7.1-6.fc29.noarch                                                                                                                                           1/6
  Erasing          : jline-2.14.6-3.fc29.noarch                                                                                                                                            2/6
  Erasing          : jansi-1.17.1-2.fc29.noarch                                                                                                                                            3/6
  Erasing          : jansi-native-1.7-7.fc29.x86_64                                                                                                                                        4/6
  Erasing          : hawtjni-runtime-1.16-3.fc29.noarch                                                                                                                                    5/6
  Erasing          : javapackages-tools-5.3.0-1.fc29.noarch                                                                                                                                6/6
  Running scriptlet: javapackages-tools-5.3.0-1.fc29.noarch                                                                                                                                6/6
  Verifying        : hawtjni-runtime-1.16-3.fc29.noarch                                                                                                                                    1/6
  Verifying        : jansi-1.17.1-2.fc29.noarch                                                                                                                                            2/6
  Verifying        : jansi-native-1.7-7.fc29.x86_64                                                                                                                                        3/6
  Verifying        : javapackages-tools-5.3.0-1.fc29.noarch                                                                                                                                4/6
  Verifying        : jline-2.14.6-3.fc29.noarch                                                                                                                                            5/6
  Verifying        : rhino-1.7.7.1-6.fc29.noarch                                                                                                                                           6/6

Removed:
  rhino-1.7.7.1-6.fc29.noarch hawtjni-runtime-1.16-3.fc29.noarch jansi-1.17.1-2.fc29.noarch jansi-native-1.7-7.fc29.x86_64 javapackages-tools-5.3.0-1.fc29.noarch jline-2.14.6-3.fc29.noarch

Complete!
[kus@localhost jonah]$