import forms module
test should pass now

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\kus\Documents\src\wyoming\public-website> ng test
 10% building 2/2 modules 0 active10 08 2019 17:57:21.731:WARN [karma]: No captured browser, open http://localhost:9876/
10 08 2019 17:57:22.811:INFO [karma-server]: Karma v4.1.0 server started at http://0.0.0.0:9876/
10 08 2019 17:57:22.813:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
10 08 2019 17:57:22.833:INFO [launcher]: Starting browser Chrome                                                                46% building 308/308 modules 0 active10 08 2019 17:58:33.108:WARN [launcher]: Chrome have not captured in 60000 ms, killing.                                 48% building 319/319 modules 0 active10 08 2019 17:58:37.185:WARN [launcher]: Chrome was not killed in 2000 ms, sending SIGKILL.                                 50% building 340/340 modules 0 active10 08 2019 17:58:39.583:WARN [launcher]: Chrome was not killed by SIGKILL in 2000 ms, continuing.                          10 08 2019 17:58:58.030:WARN [karma]:
No captured browser, open http://localhost:9876/
10 08 2019 17:58:58.366:INFO [launcher]: Trying to start Chrome again (1/2).
10 08 2019 17:59:10.466:INFO [Chrome 76.0.3809 (Windows 10.0.0)]: Connected on socket He81eZFFX-0cYi_9AAAA with id 2170121
Terminate batch job (Y/N)? y
PS C:\Users\kus\Documents\src\wyoming\public-website> ng test
 10% building 2/2 modules 0 active10 08 2019 18:07:27.481:WARN [karma]: No captured browser, open http://localhost:9876/
10 08 2019 18:07:27.906:INFO [karma-server]: Karma v4.1.0 server started at http://0.0.0.0:9876/
10 08 2019 18:07:27.908:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
10 08 2019 18:07:27.933:INFO [launcher]: Starting browser Chrome                                                               10 08 2019 18:08:10.630:WARN [karma]: No captured browser, open http://localhost:9876/
10 08 2019 18:08:11.962:INFO [Chrome 76.0.3809 (Windows 10.0.0)]: Connected on socket cQh5TSIX44U6Uki3AAAA with id 28083127
Chrome 76.0.3809 (Windows 10.0.0) SearchComponent should create FAILED
                <input matInput placeholder="Placeholder" [ERROR ->][(ngModel)]="sdpSearchTextboxValue">
                <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
        Can't bind to 'ngModel' since it isn't a known property of 'input'. ("        <mat-label>Outline form field</mat-label>
                <input matInput placeholder="Placeholder" [ERROR ->][(ngModel)]="sdpSearchTextboxValue">
                <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
        "): ng:///DynamicTestModule/SearchFormComponent.html@3:50
        error properties: Object({ ngSyntaxError: true, ngParseErrors: [ Can't bind to 'ngModel' since it isn't a known property of 'input'. ("        <mat-label>Outline form field</mat-label>
        "): ng:///DynamicTestModule/SearchFormComponent.html@3:50 ] })
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:2175:1)
            at TemplateParser.parse (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:11188:1)
            at JitCompiler._parseTemplate (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25721:1)
            at JitCompiler._compileTemplate (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25709:61)
            at http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25653:1
            at <Jasmine>
            at JitCompiler._compileComponents (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25653:1)
            at http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25573:1
            at Object.then (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:2166:27)
            at JitCompiler._compileModuleAndAllComponents (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25571:1)
                <input matInput placeholder="Placeholder" [ERROR ->][(ngModel)]="sdpSearchTextboxValue">
                <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
        Error: Template parse errors:
        Can't bind to 'ngModel' since it isn't a known property of 'input'. ("        <mat-label>Outline form field</mat-label>
                <input matInput placeholder="Placeholder" [ERROR ->][(ngModel)]="sdpSearchTextboxValue">
                <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
        "): ng:///DynamicTestModule/SearchFormComponent.html@3:50
        error properties: Object({ ngSyntaxError: true, ngParseErrors: [ Can't bind to 'ngModel' since it isn't a known property of 'input'. ("        <mat-label>Outline form field</mat-label>
        "): ng:///DynamicTestModule/SearchFormComponent.html@3:50 ] })
            at syntaxError (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:2175:1)
            at TemplateParser.parse (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:11188:1)
            at JitCompiler._parseTemplate (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25721:1)
            at JitCompiler._compileTemplate (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25709:61)
            at http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25653:1
            at <Jasmine>
            at JitCompiler._compileComponents (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25653:1)
            at http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25573:1
            at Object.then (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:2166:27)
            at JitCompiler._compileModuleAndAllComponents (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25571:1)
        Error: Expected undefined to be truthy.
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9876/src/app/search/search.component.spec.ts:39:23)
            at ZoneDelegate.invoke (http://localhost:9876/node_modules/zone.js/dist/zone-evergreen.js:359:1)
            at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/node_modules/zone.js/dist/zone-testing.js:308:1)
Chrome 76.0.3809 (Windows 10.0.0): Executed 2 of 5 (1 FAILED) (0 secs / 2.161 secs)
Chrome 76.0.3809 (Windows 10.0.0) SearchComponent should create FAILED
                <input matInput placeholder="Placeholder" [ERROR ->][(ngModel)]="sdpSearchTextboxValue">
                <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
        Can't bind to 'ngModel' since it isn't a known property of 'input'. ("        <mat-label>Outline form field</mat-label>
                <input matInput placeholder="Placeholder" [ERROR ->][(ngModel)]="sdpSearchTextboxValue">
                <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
        "): ng:///DynamicTestModule/SearchFormComponent.html@3:50
        error properties: Object({ ngSyntaxError: true, ngParseErrors: [ Can't bind to 'ngModel' since it isn't a known property of 'input'. ("        <mat-label>Outline form field</mat-label>
        "): ng:///DynamicTestModule/SearchFormComponent.html@3:50 ] })
        Error: Template parse errors:
            at syntaxError (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:2175:1)
            at TemplateParser.parse (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:11188:1)
            at JitCompiler._parseTemplate (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25721:1)
            at JitCompiler._compileTemplate (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25709:61)
            at http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25653:1
            at <Jasmine>
            at JitCompiler._compileComponents (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25653:1)
            at http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25573:1
            at Object.then (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:2166:27)
            at JitCompiler._compileModuleAndAllComponents (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25571:1)
                <input matInput placeholder="Placeholder" [ERROR ->][(ngModel)]="sdpSearchTextboxValue">
                <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
        Error: Template parse errors:
        Can't bind to 'ngModel' since it isn't a known property of 'input'. ("        <mat-label>Outline form field</mat-label>
                <input matInput placeholder="Placeholder" [ERROR ->][(ngModel)]="sdpSearchTextboxValue">
                <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
        "): ng:///DynamicTestModule/SearchFormComponent.html@3:50
        error properties: Object({ ngSyntaxError: true, ngParseErrors: [ Can't bind to 'ngModel' since it isn't a known property of 'input'. ("        <mat-label>Outline form field</mat-label>
        "): ng:///DynamicTestModule/SearchFormComponent.html@3:50 ] })
            at syntaxError (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:2175:1)
            at TemplateParser.parse (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:11188:1)
            at JitCompiler._parseTemplate (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25721:1)
            at JitCompiler._compileTemplate (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25709:61)
            at http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25653:1
            at <Jasmine>
            at JitCompiler._compileComponents (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25653:1)
            at http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25573:1
            at Object.then (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:2166:27)
            at JitCompiler._compileModuleAndAllComponents (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:25571:1)
        Error: Expected undefined to be truthy.
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9876/src/app/search/search.component.spec.ts:39:23)
            at ZoneDelegate.invoke (http://localhost:9876/node_modules/zone.js/dist/zone-evergreen.js:359:1)
            at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/node_modules/zone.js/dist/zone-testinLOG: undefinedLOG: undefined
Chrome 76.0.3809 (Windows 10.0.0): Executed 2 of 5 (1 FAILED) (0 secs / 2.161 secs)
Chrome 76.0.3809 (Windows 10.0.0): Executed 5 of 5 (1 FAILED) (4.47 secs / 4.169 secs)
TOTAL: 1 FAILED, 4 SUCCESS
TOTAL: 1 FAILED, 4 SUCCESS
LOG: undefined
Chrome 76.0.3809 (Windows 10.0.0): Executed 2 of 5 SUCCESS (0 secs / 2.229 secs)
LOG: undefined
Chrome 76.0.3809 (Windows 10.0.0): Executed 3 of 5 SUCCESS (0 secs / 2.985 secs)
Chrome 76.0.3809 (Windows 10.0.0): Executed 5 of 5 SUCCESS (3.724 secs / 3.486 secs)
TOTAL: 5 SUCCESS
TOTAL: 5 SUCCESS