revert change to use pipenv
From https://gitlab.com/wyoming/wyoming.gitlab.io
 * branch            master     -> FETCH_HEAD
   2d1e044..9d92629  master     -> origin/master
Updating 2d1e044..9d92629
Fast-forward
 experimental/python/buford/Dockerfile       | 7 +++++--
 experimental/python/buford/requirements.txt | 6 ++++++
 2 files changed, 11 insertions(+), 2 deletions(-)
Removing letsencrypt-nginx-proxy-companion ... done
Removing nginx-gen                         ... done
Removing nginx                             ... done
Removing buford                            ... done
Removing network buford_default
Creating network "buford_default" with the default driver
Building buford
Step 1/15 : FROM python:stretch
Trying to pull repository docker.io/library/python ...
sha256:d080febec9e26885db2e569d2dee9bd0b1117fb2e219241ac33d118887f7cb94: Pulling from docker.io/library/python
Digest: sha256:d080febec9e26885db2e569d2dee9bd0b1117fb2e219241ac33d118887f7cb94
Status: Image is up to date for docker.io/python:stretch
 ---> ac069ebfe1e1
Step 2/15 : RUN apt-get update
 ---> Using cache
 ---> 58ae2196bedc
Step 3/15 : RUN apt-get upgrade -y
 ---> Using cache
 ---> 2272524d1ad4
Step 4/15 : RUN apt-get -y install build-essential python3-psycopg2
 ---> Using cache
 ---> 7561814720f1
Step 5/15 : RUN mkdir -p /var/www/
 ---> Using cache
 ---> 4316af492792
Step 6/15 : WORKDIR /var/www/
 ---> Using cache
 ---> dbcd3d828bc2
Step 7/15 : ADD . /var/www
 ---> 23f0c81f95ca
Removing intermediate container 402f56fdb378
Step 8/15 : RUN pip install --upgrade pip setuptools
 ---> Running in 6e98b721efc5
Requirement already up-to-date: pip in /usr/local/lib/python3.7/site-packages (19.0.2)
Requirement already up-to-date: setuptools in /usr/local/lib/python3.7/site-packages (40.8.0)
 ---> f696a422bd31
Removing intermediate container 6e98b721efc5
Step 9/15 : RUN pip install --user pipenv
 ---> Running in 711c6f29f416
Collecting pipenv
  Downloading https://files.pythonhosted.org/packages/13/b4/3ffa55f77161cff9a5220f162670f7c5eb00df52e00939e203f601b0f579/pipenv-2018.11.26-py3-none-any.whl (5.2MB)
Requirement already satisfied: pip>=9.0.1 in /usr/local/lib/python3.7/site-packages (from pipenv) (19.0.2)
Collecting certifi (from pipenv)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
Collecting virtualenv (from pipenv)
  Downloading https://files.pythonhosted.org/packages/7e/1b/6c00d57127608793e16e8b7f813e64d58a1938505c42fe190d1386ab41e1/virtualenv-16.4.0-py2.py3-none-any.whl (2.0MB)
Requirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.7/site-packages (from pipenv) (40.8.0)
Collecting virtualenv-clone>=0.2.5 (from pipenv)
  Downloading https://files.pythonhosted.org/packages/e3/d9/d9c56deb483c4d3289a00b12046e41428be64e8236fa210111a1f57cc42d/virtualenv_clone-0.5.1-py2.py3-none-any.whl
Installing collected packages: certifi, virtualenv, virtualenv-clone, pipenv
  The script virtualenv is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script virtualenv-clone is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The scripts pipenv and pipenv-resolver are installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed certifi-2018.11.29 pipenv-2018.11.26 virtualenv-16.4.0 virtualenv-clone-0.5.1
 ---> 000cee865acc
Removing intermediate container 711c6f29f416
Step 10/15 : RUN export PATH="$HOME/.local/bin:$PATH"
 ---> Running in f1516498641f
 ---> bf043baf80bf
Removing intermediate container f1516498641f
Step 11/15 : RUN pipenv install
 ---> Running in 4ec07111d06c
/bin/sh: 1: pipenv: not found
ERROR: Service 'buford' failed to build: The command '/bin/sh -c pipenv install' returned a non-zero code: 127