run ng lint
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\kus\Documents\src\wyoming\public-website> ng e2e
[07:31:03] I/file_manager - creating folder C:\Users\kus\Documents\src\wyoming\public-website\node_modules\webdriver-manager\selenium
[07:31:03] I/config_source - curl -oC:\Users\kus\Documents\src\wyoming\public-website\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
[07:31:05] I/downloader - curl -oC:\Users\kus\Documents\src\wyoming\public-website\node_modules\webdriver-manager\selenium/chromedriver_75.0.3770.140.zip https://chromedriver.storage.googleapis.com/75.0.3770.140/chromedriver_win32.zip
[07:31:06] I/update - chromedriver: unzipping chromedriver_75.0.3770.140.zip
An unhandled exception occurred: Port 4200 is already in use. Use '--port' to specify a different port.
See "C:\Users\kus\AppData\Local\Temp\ng-hOr0vX\angular-errors.log" for further details.
PS C:\Users\kus\Documents\src\wyoming\public-website> ng e2e --port 9875
[07:32:43] I/update - chromedriver: file exists C:\Users\kus\Documents\src\wyoming\public-website\node_modules\webdriver-manager\selenium\chromedriver_75.0.3770.140.zip
[07:32:43] I/update - chromedriver: unzipping chromedriver_75.0.3770.140.zip
[07:32:44] I/update - chromedriver: chromedriver_75.0.3770.140.exe up to date
 10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:9875/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.htmlchunk {main} main.js, main.js.map (main) 11 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 278 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 407 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.45 MB [initial] [rendered]
Date: 2019-07-27T13:34:21.297Z - Hash: 5ad134cd9adebb3f7120 - Time: 71798ms
** Angular Live Development Server is listening on localhost:9875, open your browser on http://localhost:9875/ **
i ｢wdm｣: Compiled successfully.
[07:34:23] I/launcher - Running 1 instances of WebDriver
[07:34:23] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:50769/devtools/browser/8caafd69-9f24-4596-b095-7f5c6d5ca18c
Jasmine started

  workspace-project App
    × should display welcome message
      - Failed: No element found using locator: By(css selector, app-root h1)
          at C:\Users\kus\Documents\src\wyoming\public-website\node_modules\protractor\built\element.js:814:27
          at ManagedPromise.invokeCallback_ (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\selenium-webdriver\lib\promise.js:1376:14)
          at TaskQueue.execute_ (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\selenium-webdriver\lib\promise.js:3084:14)
          at TaskQueue.executeNext_ (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\selenium-webdriver\lib\promise.js:3067:27)
          at C:\Users\kus\Documents\src\wyoming\public-website\node_modules\selenium-webdriver\lib\promise.js:2927:27
          at C:\Users\kus\Documents\src\wyoming\public-website\node_modules\selenium-webdriver\lib\promise.js:668:7
          at processTicksAndRejections (internal/process/task_queues.js:89:5)Error:
          at ElementArrayFinder.applyAction_ (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\protractor\built\element.js:459:27)
          at ElementArrayFinder.<computed> [as getText] (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\protractor\built\element.js:91:29)
          at ElementFinder.<computed> [as getText] (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\protractor\built\element.js:831:22)
          at AppPage.getTitleText (C:\Users\kus\Documents\src\wyoming\public-website\e2e\src\app.po.ts:9:43)
          at UserContext.<anonymous> (C:\Users\kus\Documents\src\wyoming\public-website\e2e\src\app.e2e-spec.ts:13:17)
          at new ManagedPromise (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\selenium-webdriver\lib\promise.js:1077:7)
          at ControlFlow.promise (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\selenium-webdriver\lib\promise.js:2505:12)
          at TaskQueue.execute_ (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\selenium-webdriver\lib\promise.js:3084:14)
      From: Task: Run it("should display welcome message") in control flow
          at ControlFlow.emit (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\selenium-webdriver\lib\events.js:62:21)
          at ControlFlow.shutdown_ (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\selenium-webdriver\lib\promise.js:2674:10)
          at C:\Users\kus\Documents\src\wyoming\public-website\node_modules\selenium-webdriver\lib\promise.js:2599:53
      From asynchronous test:
      Error:
          at Suite.<anonymous> (C:\Users\kus\Documents\src\wyoming\public-website\e2e\src\app.e2e-spec.ts:11:3)
          at Object.<anonymous> (C:\Users\kus\Documents\src\wyoming\public-website\e2e\src\app.e2e-spec.ts:4:1)
          at Module._compile (internal/modules/cjs/loader.js:774:30)
          at Module.m._compile (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\ts-node\src\index.ts:439:23)
          at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
          at Object.require.extensions.<computed> [as .ts] (C:\Users\kus\Documents\src\wyoming\public-website\node_modules\ts-node\src\index.ts:442:12)

**************************************************
*                    Failures                    *
**************************************************

1) workspace-project App should display welcome message
  - Failed: No element found using locator: By(css selector, app-root h1)

Executed 1 of 1 spec (1 FAILED) in 6 secs.
[07:34:51] I/launcher - 0 instance(s) of WebDriver still running
[07:34:51] I/launcher - chrome #01 failed 1 test(s)
[07:34:51] I/launcher - overall: 1 failed spec(s)
[07:34:51] E/launcher - Process exited with error code 1
PS C:\Users\kus\Documents\src\wyoming\public-website> ng e2e --port 9875
[07:35:23] I/update - chromedriver: file exists C:\Users\kus\Documents\src\wyoming\public-website\node_modules\webdriver-manager\selenium\chromedriver_75.0.3770.140.zip
[07:35:23] I/update - chromedriver: unzipping chromedriver_75.0.3770.140.zip
[07:35:23] I/update - chromedriver: chromedriver_75.0.3770.140.exe up to date
 10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:9875/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.htmlchunk {main} main.js, main.js.map (main) 11 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 278 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 407 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.45 MB [initial] [rendered]
Date: 2019-07-27T13:36:10.568Z - Hash: 5ad134cd9adebb3f7120 - Time: 39061ms
** Angular Live Development Server is listening on localhost:9875, open your browser on http://localhost:9875/ **
i ｢wdm｣: Compiled successfully.
[07:36:11] I/launcher - Running 1 instances of WebDriver
[07:36:11] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:50822/devtools/browser/f0d1c703-e31d-43ea-9237-ea95fb803853
Jasmine started

Executed 0 of 0 specs SUCCESS in 0.011 sec.
[07:36:21] I/launcher - 0 instance(s) of WebDriver still running
[07:36:21] I/launcher - chrome #01 passed
PS C:\Users\kus\Documents\src\wyoming\public-website> Measure-Command { ng e2e }
PS C:\Users\kus\Documents\src\wyoming\public-website> Measure-Command { ng e2e --port 9875 }

DevTools listening on ws://127.0.0.1:50851/devtools/browser/9dec29a3-a1da-4f5b-a90c-bfe4f9903928

Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 14
Milliseconds      : 704
Ticks             : 747040712
TotalDays         : 0.000864630453703704
TotalHours        : 0.0207511308888889
TotalMinutes      : 1.24506785333333
TotalSeconds      : 74.7040712
TotalMilliseconds : 74704.0712

PS C:\Users\kus\Documents\src\wyoming\public-website> Measure-Command { ng lint }
Lint errors found in the listed files.

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 28
Milliseconds      : 335
Ticks             : 283353342
TotalDays         : 0.000327955256944444
TotalHours        : 0.00787092616666667
TotalMinutes      : 0.47225557
TotalSeconds      : 28.3353342
TotalMilliseconds : 28335.3342

PS C:\Users\kus\Documents\src\wyoming\public-website> Measure-Command { ng lint --fix }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 47
Milliseconds      : 839
Ticks             : 478394614
TotalDays         : 0.000553697469907407
TotalHours        : 0.0132887392777778
TotalMinutes      : 0.797324356666667
TotalSeconds      : 47.8394614
TotalMilliseconds : 47839.4614

PS C:\Users\kus\Documents\src\wyoming\public-website>