fix push fails
$ git remote set-url origin ssh://kus@mynepal.duckdns.org:/home/kus/Documents/wyoming
$ git push origin --all
Warning: Permanently added 'mynepal.duckdns.org,108.35.63.209' (ECDSA) to the list of known hosts.
remote: error: refusing to update checked out branch: refs/heads/master
remote: error: By default, updating the current branch in a non-bare repository
remote: is denied, because it will make the index and work tree inconsistent
remote: with what you pushed, and will require 'git reset --hard' to match
remote: the work tree to HEAD.
remote:
remote: You can set the 'receive.denyCurrentBranch' configuration variable
remote: to 'ignore' or 'warn' in the remote repository to allow pushing into
remote: its current branch; however, this is not recommended unless you
remote: arranged to update its work tree to match what you pushed in some
remote: other way.
remote:
remote: To squelch this message and still keep the default behaviour, set
remote: 'receive.denyCurrentBranch' configuration variable to 'refuse'.
To ssh://mynepal.duckdns.org:/home/kus/Documents/wyoming
 ! [remote rejected] master -> master (branch is currently checked out)
error: failed to push some refs to 'ssh://kus@mynepal.duckdns.org:/home/kus/Documents/wyoming'
ERROR: Job failed: exit code 1

https://gitlab.com/wyoming/wyoming.gitlab.io/-/jobs/165327489